const libros = [
	{
		ISBN: '9788484600572',
		NombreLibro: 'GRAN ENCICLOPEDIA DEL DISPARATE',
		Autor: 'JOSE RODRIGUEZ PASENCIA',
		Edicion: 'Primera',
		Categoria: 'Humor',
		Estado: 'Usado',
		Precio: 6000,
	},
	{
		ISBN: '9788408118657',
		NombreLibro: 'NO ESTAMOS LOCOS',
		Autor: 'José Miguel Monzón',
		Edicion: 'Septima',
		Categoria: 'Humor',
		Estado: 'Usado',
		Precio: 12000,
	},	
	{
		ISBN: '9788439727903',
		NombreLibro: 'A CADA UNO LO SUYO',
		Autor: ' EL ROTO',
		Edicion: 'Tercera',
		Categoria: 'Humor',
		Estado: 'Nuevo',
		Precio: 25000,
	},
	{
		ISBN: '9788478806041',
		NombreLibro: 'EL GRAN LIBRO INOCENTE INOCENTE.',
		Autor: 'FERNANDO (COLABORAD VIZCAINO CASAS',
		Edicion: 'Segunda',
		Categoria: 'Humor',
		Estado: 'Usado',
		Precio: 8000,
	},
	{
		ISBN: '9788408292357',
		NombreLibro: 'DÍAS DE PERROS',
		Autor: 'GILLES LEGARDINIER',
		Edicion: 'Primera',
		Categoria: 'Humor',
		Estado: 'Nuevo',
		Precio: 30000,
	},
	{
		ISBN: '9788419456793',
		NombreLibro: 'PERDIDAS EN EL BOSQUE',
		Autor: 'MARGARET ATWOOD',
		Edicion: 'Primera',
		Estado: 'Nuevo',
		Categoria: 'Literatura',
		Precio: 39000,
	},
	{
		ISBN: '9788425367755',
		NombreLibro: 'EL GATO QUE CUIDABA LAS BIBLIOTECAS',
		Autor: 'SOSUKE NATSUKAWA',
		Edicion: 'Primera',
		Categoria: 'Literatura',
		Estado: 'Usado',
		Precio: 28000,
	},
	{
		ISBN: '9788419581693',
		NombreLibro: 'MATAMONSTRUOS',
		Autor: 'JON BILBAO',
		Edicion: 'Primera',
		Categoria: 'Literatura',
		Estado: 'Usado',
		Precio: 21000,
	},
	{
		ISBN: '9788467072662',
		NombreLibro: 'EL ÁRBOL DE LAS PALABRAS',
		Autor: 'ANDRES PASCUAL',
		Edicion: 'Cuarta',
		Categoria: 'Literatura',
		Estado: 'Usado',
		Precio: 20000,
	},
	{
		ISBN: '9788491294283',
		NombreLibro: 'LA ASISTENTA',
		Autor: 'FREIDA MCFADDEN',
		Edicion: 'Segunda',
		Categoria: 'Literatura',
		Estado: 'Usado',
		Precio: 18000,
	},
	{
		ISBN: '9788425361777',
		NombreLibro: 'LAS GAFAS DE LA FELICIDAD ED. ACTUALIZADA',
		Autor: 'RAFAEL SANTANDREU',
		Edicion: 'Sexta',
		Categoria: 'Hobby',
		Estado: 'Usado',
		Precio: 18000,
	},
	{
		ISBN: '9788494729645',
		NombreLibro: 'HOY TE QUIERO MÁS QUE AYER, YA MAÑANA SE VERÁ',
		Autor: 'BENITO TROYA',
		Edicion: 'Tercera',
		Categoria: 'Hobby',
		Estado: 'Usado',
		Precio: 5000,
	},
	{
		ISBN: '9788432243950',
		NombreLibro: 'NO TE VERE MORIR',
		Autor: 'ANTONIO MUÑOZ MOLINA',
		Edicion: 'Primera',
		Categoria: 'Hobby',
		Estado: 'Nuevo',
		Precio: 35000,
	},
	{
		ISBN: '9788408261902',
		NombreLibro: 'A TRAMPA DE LA FELICIDAD: LIBERATE DE LA ANSIEDAD. EMPIEZA A VIVIR',
		Autor: 'RUSS HARRIS',
		Edicion: 'Cuarta',
		Categoria: 'Hobby',
		Estado: 'Usado',
		Precio: 27000,
	},
	{
		ISBN: '9788401030895',
		NombreLibro: 'GUARDA SILENCIO',
		Autor: 'LORENA GONZALEZ',
		Edicion: 'Primera',
		Categoria: 'Hobby',
		Estado: 'Nuevo',
		Precio: 30000,
	},
	{
		ISBN: '9788432244131',
		NombreLibro: 'ODAS ELEMENTALES',
		Autor: 'PABLO NERUDA',
		Edicion: 'Sexta',
		Categoria: 'Poesia',
		Estado: 'Nuevo',
		Precio: 38000,
	},
	{
		ISBN: '9788498955873',
		NombreLibro: 'EL CIELO SIN CAMINOS',
		Autor: 'SERGIO FERNANDEZ SALVADOR',
		Edicion: 'Quinta',
		Categoria: 'Poesia',
		Estado: 'Usado',
		Precio: 19000,
	},
	{
		ISBN: '9788467065848',
		NombreLibro: 'OJALA',
		Autor: 'DEFREDS JOSE. A. GOMEZ IGLESIAS',
		Edicion: 'Tercera',
		Categoria: 'Poesia',
		Estado: 'Nuevo',
		Precio: 41000,
	},
	{
		ISBN: '9788498955088',
		NombreLibro: 'EL SECRETO DEL MAGO',
		Autor: 'LUIS ALBERTO DE CUENCA',
		Edicion: 'Septima',
		Categoria: 'Poesia',
		Estado: 'Usado',
		Precio: 21000,
	},
	{
		ISBN: '9788494956171',
		NombreLibro: 'QUERIDA ANSIEDAD',
		Autor: 'NIÑATO',
		Edicion: 'Tercera',
		Categoria: 'Poesia',
		Estado: 'Nuevo',
		Precio: 24000,
	}
];
